name: turbo
description: A simple, efficient state management solution for Flutter...
version: 1.2.1
homepage: https://github.com/aldrinsartfactory/turbo
repository: https://github.com/aldrinsartfactory/turbo
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: null